name: Generate Snake Animation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/github-contribution-grid-snake.svg

      - name: Push Snake to Repository
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          message: "Generate contribution grid snake"
          add: dist/github-contribution-grid-snake.svg
